# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Tudsbury - Web Developer
email: james@jtudsbury.com
description: Portfolio website of Mannchester based front end web developer James Tudsbury.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jtuds
github_username:  jtuds

# Build settings
markdown: kramdown
